import Head from 'next/head'
import { sanityClient } from '../sanity';
import Navbar from '../components/Home/Navbar'
import HeroSection from '../components/Home/HeroSection'
import HeroImage from '../components/Home/HeroImage';
import OurTools from '../components/Home/OurTools';
import Service from '../components/Home/Service';
import CompleteSEO from '../components/Home/CompleteSEO';
import Testimonial from '../components/Home/Testimonial';
import CompanyStart from '../components/Home/CompanyStart';
import Footer from '../components/Home/Footer';
import Review from '../components/Home/Review';


export default function Home({properties}) {
  
  return (
    <div>
      <Head>
        <title>Bright Local SEO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Navbar />
      <HeroSection />
      <HeroImage />
      <OurTools />
      <Service />
      <CompleteSEO />
      <Testimonial properties={properties} />
      <CompanyStart />
      <Footer />
      <Review />
    </div>
  )
}

export const getServerSideProps = async () => {
    const query = '*[ _type == "property"]'
    const properties = await sanityClient.fetch(query)

    if(!properties.length) {
        return {
            props: {
                properties: [],
            },
        }
    } else {
        return {
            props: {
                properties,
            }
        }
    }
}
